export interface Tool {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: 'essentials' | 'edit-organize' | 'security-privacy' | 'convert-export' | 'scan-share' | 'business';
  icon: string;
  popular?: boolean;
  new?: boolean;
}

export const CATEGORIES = [
  { id: 'essentials', name: 'Essentials', icon: 'Sparkles', description: 'Core PDF tasks you use every day' },
  { id: 'edit-organize', name: 'Edit & Organize', icon: 'Edit3', description: 'Modify, reorder, crop, and annotate pages' },
  { id: 'security-privacy', name: 'Security & Privacy', icon: 'Shield', description: 'Encrypt, redact, flatten, and sanitize PDFs' },
  { id: 'convert-export', name: 'Convert & Export', icon: 'ArrowLeftRight', description: 'Convert PDFs to/from Office, HTML, images & e-books' },
  { id: 'scan-share', name: 'Scan & Share', icon: 'Camera', description: 'Webcam scanning, P2P transfer & live whiteboard' },
  { id: 'business', name: 'Business Suite', icon: 'Briefcase', description: 'Invoices, receipt billing & document fingerprinting' },
] as const;

export const TOOLS: Tool[] = [
  // 🟢 Essentials
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: 'merge-pdf',
    description: 'Combine multiple PDF files into one structured document in seconds.',
    category: 'essentials',
    icon: 'Combine',
    popular: true,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: 'compress-pdf',
    description: 'Reduce PDF file size while maintaining maximum visual quality.',
    category: 'essentials',
    icon: 'Minimize2',
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: 'split-pdf',
    description: 'Extract specific page ranges or split each page into separate files.',
    category: 'essentials',
    icon: 'Scissors',
    popular: true,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    description: 'Convert PDF pages into high-resolution JPG or PNG images.',
    category: 'essentials',
    icon: 'FileImage',
    popular: true,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    slug: 'word-to-pdf',
    description: 'Convert Microsoft Word (.docx/.doc) documents into standard PDFs.',
    category: 'essentials',
    icon: 'FileText',
    popular: true,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    slug: 'pdf-to-word',
    description: 'Extract text and layout from PDF into editable Word (.docx) documents.',
    category: 'essentials',
    icon: 'FileCode',
    popular: true,
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    slug: 'images-to-pdf',
    description: 'Convert JPG, PNG, WEBP images into a single clean PDF document.',
    category: 'essentials',
    icon: 'Images',
    popular: true,
  },

  // ✏️ Edit & Organize
  {
    id: 'edit-pdf-text',
    name: 'Edit PDF Text',
    slug: 'edit-pdf-text',
    description: 'Add text boxes, draw signatures, insert images, and make direct edits.',
    category: 'edit-organize',
    icon: 'PenTool',
    popular: true,
  },
  {
    id: 'organize-pages',
    name: 'Organize Pages',
    slug: 'organize-pages',
    description: 'Reorder, rotate, delete, or rearrange pages with drag and drop.',
    category: 'edit-organize',
    icon: 'LayoutGrid',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    description: 'Rotate individual pages or entire documents 90°, 180°, or 270°.',
    category: 'edit-organize',
    icon: 'RotateCw',
  },
  {
    id: 'crop-resize-pdf',
    name: 'Crop & Resize',
    slug: 'crop-resize-pdf',
    description: 'Crop margins and resize pages to standard A4, Letter, or custom bounds.',
    category: 'edit-organize',
    icon: 'Crop',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    slug: 'add-watermark',
    description: 'Stamp custom text or image watermarks with full opacity & angle control.',
    category: 'edit-organize',
    icon: 'Stamp',
  },
  {
    id: 'page-numbers',
    name: 'Add Page Numbers',
    slug: 'page-numbers',
    description: 'Insert customizable page numbering, headers, footers, and formatting.',
    category: 'edit-organize',
    icon: 'Hash',
  },
  {
    id: 'headers-footers',
    name: 'Headers & Footers',
    slug: 'headers-footers',
    description: 'Add dynamic running headers, footers, dates, and title tokens to pages.',
    category: 'edit-organize',
    icon: 'PanelTop',
  },
  {
    id: 'extract-text',
    name: 'Extract Text',
    slug: 'extract-text',
    description: 'Copy or export raw plain text content from selectable PDF text layers.',
    category: 'edit-organize',
    icon: 'FileSpreadsheet',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR Searchable PDF',
    slug: 'ocr-pdf',
    description: 'Recognize scanned text using Tesseract WASM to make PDFs selectable & searchable.',
    category: 'edit-organize',
    icon: 'ScanText',
    popular: true,
  },

  // 🔐 Security & Privacy
  {
    id: 'encrypt-pdf',
    name: 'Encrypt PDF',
    slug: 'encrypt-pdf',
    description: 'Protect your sensitive documents with robust AES-256 password encryption.',
    category: 'security-privacy',
    icon: 'Lock',
    popular: true,
  },
  {
    id: 'remove-password',
    name: 'Remove Password',
    slug: 'remove-password',
    description: 'Unlock and remove password restriction from PDFs directly in your browser.',
    category: 'security-privacy',
    icon: 'Unlock',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    slug: 'redact-pdf',
    description: 'Permanently block out and sanitize confidential content from document pages.',
    category: 'security-privacy',
    icon: 'EyeOff',
    popular: true,
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    slug: 'flatten-pdf',
    description: 'Burn form fields, annotations, and scripts into unmodifiable page graphics.',
    category: 'security-privacy',
    icon: 'Layers',
  },
  {
    id: 'privacy-scanner',
    name: 'Privacy Risk Scanner',
    slug: 'privacy-scanner',
    description: 'Inspect and strip hidden author data, EXIF tags, GPS metadata, and revision logs.',
    category: 'security-privacy',
    icon: 'ShieldCheck',
    new: true,
  },

  // 🔄 Convert & Export
  {
    id: 'create-pdf',
    name: 'Create PDF',
    slug: 'create-pdf',
    description: 'Compose and format new documents using a built-in rich text editor.',
    category: 'convert-export',
    icon: 'FilePlus',
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    slug: 'markdown-to-pdf',
    description: 'Convert Markdown text and files into beautifully formatted PDF documents.',
    category: 'convert-export',
    icon: 'FileCode2',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    slug: 'html-to-pdf',
    description: 'Render web pages or raw HTML snippets directly into PDF format.',
    category: 'convert-export',
    icon: 'Code',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    slug: 'excel-to-pdf',
    description: 'Convert XLSX and XLS spreadsheets into formatted PDF tables.',
    category: 'convert-export',
    icon: 'Table',
  },
  {
    id: 'csv-to-pdf',
    name: 'CSV to PDF',
    slug: 'csv-to-pdf',
    description: 'Convert comma-separated data files into styled PDF data tables.',
    category: 'convert-export',
    icon: 'FileDigit',
  },
  {
    id: 'pptx-to-pdf',
    name: 'PowerPoint to PDF',
    slug: 'pptx-to-pdf',
    description: 'Convert PPTX presentation slide decks into portable PDF documents.',
    category: 'convert-export',
    icon: 'Presentation',
  },
  {
    id: 'pdf-to-pptx',
    name: 'PDF to PowerPoint',
    slug: 'pdf-to-pptx',
    description: 'Convert each PDF page into editable presentation slide frames.',
    category: 'convert-export',
    icon: 'Tv2',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    slug: 'pdf-to-excel',
    description: 'Detect and extract table data from PDF into structured Excel sheets.',
    category: 'convert-export',
    icon: 'Sheet',
  },
  {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    slug: 'pdf-to-html',
    description: 'Export PDF content as responsive, semantic web page markup.',
    category: 'convert-export',
    icon: 'Globe',
  },
  {
    id: 'pdf-to-epub',
    name: 'PDF to EPUB',
    slug: 'pdf-to-epub',
    description: 'Convert documents into EPUB e-book format for mobile e-readers.',
    category: 'convert-export',
    icon: 'BookOpen',
  },
  {
    id: 'ebook-to-pdf',
    name: 'eBook to PDF',
    slug: 'ebook-to-pdf',
    description: 'Convert EPUB, MOBI, or AZW3 e-books into printable PDF format.',
    category: 'convert-export',
    icon: 'BookMarked',
  },
  {
    id: 'pdf-to-audio',
    name: 'PDF to Audio',
    slug: 'pdf-to-audio',
    description: 'Listen to document text via browser Web Speech synthesis & export audio.',
    category: 'convert-export',
    icon: 'Volume2',
  },
  {
    id: 'audio-to-pdf',
    name: 'Audio Speech to PDF',
    slug: 'audio-to-pdf',
    description: 'Transcribe spoken audio streams into structured text PDFs.',
    category: 'convert-export',
    icon: 'Mic',
  },
  {
    id: 'pdf-to-zip',
    name: 'PDF to ZIP Archive',
    slug: 'pdf-to-zip',
    description: 'Render every PDF page into high-res images packed into a ZIP archive.',
    category: 'convert-export',
    icon: 'FolderArchive',
  },
  {
    id: 'invert-pdf',
    name: 'Invert PDF Colors',
    slug: 'invert-pdf',
    description: 'Apply dark mode or sepia reading filters while keeping text selectable.',
    category: 'convert-export',
    icon: 'Moon',
  },

  // 📷 Scan & Share
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    slug: 'scan-to-pdf',
    description: 'Capture documents with your device camera, crop, and bundle as PDF.',
    category: 'scan-share',
    icon: 'Camera',
    popular: true,
  },
  {
    id: 'p2p-share',
    name: 'P2P Private Share',
    slug: 'p2p-share',
    description: 'Direct browser-to-browser WebRTC file transfer with end-to-end privacy.',
    category: 'scan-share',
    icon: 'Share2',
  },
  {
    id: 'collab-whiteboard',
    name: 'Collaborative Whiteboard',
    slug: 'collab-whiteboard',
    description: 'Draw and mark up PDFs in real-time with peers over peer-to-peer data channels.',
    category: 'scan-share',
    icon: 'Users',
    new: true,
  },

  // 🧾 Business
  {
    id: 'gst-invoice',
    name: 'GST Invoice Generator',
    slug: 'gst-invoice',
    description: 'Create professional tax invoices with auto-calculated CGST, SGST, IGST.',
    category: 'business',
    icon: 'Receipt',
    popular: true,
  },
  {
    id: 'pos-billing',
    name: 'POS Thermal Billing',
    slug: 'pos-billing',
    description: 'Fast product checkout billing with thermal receipt printer format output.',
    category: 'business',
    icon: 'Printer',
  },
  {
    id: 'fingerprint-pdf',
    name: 'Fingerprint PDF',
    slug: 'fingerprint-pdf',
    description: 'Embed invisible steganographic tracking marks to trace document leaks.',
    category: 'business',
    icon: 'Fingerprint',
    new: true,
  },
  {
    id: 'compare-pdfs',
    name: 'Compare PDFs',
    slug: 'compare-pdfs',
    description: 'Side-by-side synchronized view with automatic algorithmic text diffing.',
    category: 'business',
    icon: 'GitCompare',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    slug: 'repair-pdf',
    description: 'Rebuild damaged cross-reference tables and recover corrupted streams.',
    category: 'business',
    icon: 'Wrench',
  },
];
